Repository LexasCMS/ember-data-lexascms, pull requests merged in 2020-07, with the labels that each got.

#1 Reduce NPM package size
  .npmignore
Labels: internal

#2 Document release instructions
  RELEASE.md
  package.json
Labels: documentation

#4 Fix package dependencies
  package.json
Labels: bug
